name: template_example-dev
services:
  postgres_db:
    image: postgres:alpine
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: template_example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    restart: on-failure
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    volumes:
      - victoria-metrics-data:/victoria-metrics-data
      - ./assets/configs/dev/promscrape.victoriametrics.yml:/scrape.yml
    command:
      - "-enableMetadata"
      - "-httpListenAddr=:8428"
      - "-opentelemetry.convertMetricNamesToPrometheus=true"
      - "-opentelemetry.usePrometheusNaming=true"
      - "-promscrape.config=/scrape.yml"
      - "-retentionPeriod=1d"
      - "-storageDataPath=/victoria-metrics-data"
    ports:
      - "8428:8428"
  victoria-logs:
    image: victoriametrics/victoria-logs:latest
    volumes:
      - victoria-logs-data:/victoria-logs-data
    command:
      - "-futureRetention=1h"
      - "-httpListenAddr=:9428"
      - "-retentionPeriod=1d"
      - "-storageDataPath=/victoria-logs-data"
    ports:
      - "9428:9428"
  victoria-traces:
    image: victoriametrics/victoria-traces:latest
    volumes:
      - victoria-traces-data:/victoria-traces-data
    command:
      - "-httpListenAddr=:10428"
      - "-retentionPeriod=1d"
      - "-storageDataPath=/victoria-traces-data"
    ports:
      - "10428:10428"
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./assets/configs/dev/otel-collector.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "8888:8888"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_INSTALL_PLUGINS=victoriametrics-metrics-datasource,victoriametrics-logs-datasource
    volumes:
      - ./assets/configs/dev/grafana/datasources/:/etc/grafana/provisioning/datasources
      - ./assets/configs/dev/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./assets/configs/dev/grafana/dashboards/:/etc/grafana/dashboards
      - grafana-data:/var/lib/grafana
volumes:
  postgres-data:
  redis-data:
  victoria-metrics-data:
  victoria-logs-data:
  victoria-traces-data:
  grafana-data:
