name: template_example-dev
services:
  postgres:
    image: postgres:alpine
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: template_example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    restart: on-failure
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
  mimir:
    image: grafana/mimir:latest
    command:
      - "-config.file=/etc/mimir/mimir.yaml"
    volumes:
      - mimir-data:/data
      - ./assets/configs/dev/mimir.yml:/etc/mimir/mimir.yaml
    ports:
      - "9009:9009"
  loki:
    image: grafana/loki:latest
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    volumes:
      - loki-data:/loki
      - ./assets/configs/dev/loki.yml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
  tempo:
    image: grafana/tempo:latest
    command:
      - "-config.file=/etc/tempo/tempo.yaml"
    volumes:
      - tempo-data:/var/tempo
      - ./assets/configs/dev/tempo.yml:/etc/tempo/tempo.yaml
    ports:
      - "3200:3200"
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    depends_on:
      - mimir
      - loki
      - tempo
    volumes:
      - ./assets/configs/dev/otel-collector.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "8888:8888"
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - mimir
      - loki
      - tempo
    ports:
      - "3001:3000"
    volumes:
      - ./assets/configs/dev/grafana/datasources/:/etc/grafana/provisioning/datasources
      - ./assets/configs/dev/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./assets/configs/dev/grafana/dashboards/:/etc/grafana/dashboards
      - grafana-data:/var/lib/grafana
volumes:
  postgres-data:
  redis-data:
  mimir-data:
  loki-data:
  tempo-data:
  grafana-data:
