name: template_example-prod
services:
  postgres:
    image: postgres:alpine
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  redis:
    image: redis:alpine
    restart: on-failure
    volumes:
      - redis-data:/data
  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    volumes:
      - victoria-metrics-data:/victoria-metrics-data
      - ./assets/configs/prod/prometheus.yml:/scrape.yml
    command:
      - "-enableMetadata"
      - "-httpListenAddr=:8428"
      - "-opentelemetry.convertMetricNamesToPrometheus=true"
      - "-opentelemetry.usePrometheusNaming=true"
      - "-promscrape.config=/scrape.yml"
      - "-retentionPeriod=14d"
      - "-storageDataPath=/victoria-metrics-data"
  victoria-logs:
    image: victoriametrics/victoria-logs:latest
    volumes:
      - victoria-logs-data:/victoria-logs-data
    command:
      - "-futureRetention=1h"
      - "-httpListenAddr=:9428"
      - "-retentionPeriod=14d"
      - "-storageDataPath=/victoria-logs-data"
  victoria-traces:
    image: victoriametrics/victoria-traces:latest
    volumes:
      - victoria-traces-data:/victoria-traces-data
    command:
      - "-httpListenAddr=:10428"
      - "-retentionPeriod=14d"
      - "-storageDataPath=/victoria-traces-data"
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./assets/configs/prod/otel-collector.yml:/etc/otelcol-contrib/config.yaml
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SERVER_ROOT_URL=https://${DEPLOY_DOMAIN}/grafana
      - GF_INSTALL_PLUGINS=victoriametrics-metrics-datasource,victoriametrics-logs-datasource
    volumes:
      - ./assets/configs/prod/grafana/datasources/:/etc/grafana/provisioning/datasources
      - ./assets/configs/prod/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./assets/configs/prod/grafana/dashboards/:/etc/grafana/dashboards
      - grafana-data:/var/lib/grafana
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  backend:
    image: localhost/template_example-backend
    restart: on-failure
    depends_on:
      - postgres
      - otel-collector
    environment:
      RUST_LOG: ${LOG_LEVEL}
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: template_example
      OTEL_ENDPOINT: http://otel-collector:4317
      OTEL_SERVICE_NAMESPACE: template_example
      OTEL_SERVICE_NAME: monolyth
      JWT_SECRET: ${JWT_SECRET}
      DEPLOY_DOMAIN: localhost
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  proxy:
    image: haproxy:latest
    restart: unless-stopped
    volumes:
      - ./assets/configs/prod/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - backend
      - grafana
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - "3000:3000"
volumes:
  postgres-data:
  redis-data:
  victoria-metrics-data:
  victoria-logs-data:
  victoria-traces-data:
  grafana-data:
