[package]
name = "template_example"
version = "0.1.0"
edition.workspace = true
publish = false
authors.workspace = true

[[bin]]
name = "template_example-monolyth"
path = "./src/bin/monolyth.rs"

[[bin]]
name = "template_example-metadata"
path = "./src/bin/metadata.rs"

[dependencies]
lib = { workspace = true, features = [
  "application",
  "bootstrap-openapi",
  "bootstrap-redis",
  "bootstrap-sqlx",
  # "bootstrap-instrumentation-stdout",
  "bootstrap-instrumentation-opentelemetry-grpc-tonic",
  "domain",
  "infrastructure-persistence-redis",
  "infrastructure-persistence-sqlx",
  "infrastructure-services",
  "macros-proc",
  "presentation-api-rest-openapi",
  "presentation-api-rest-opentelemetry",
] }
argon2 = { version = "0.5", features = ["std"] }
axum = { workspace = true, features = ["macros"] }
axum-extra = { version = "0.12", features = ["typed-header"] }
bon.workspace = true
derive_more = { workspace = true, features = ["from", "into"] }
entrait.workspace = true
fromenv.workspace = true
jsonwebtoken = { version = "11.0", default-features = false, features = [
  "rust_crypto",
] }
model-mapper.workspace = true
redis = { version = "1.0", default-features = false, features = ["uuid"] }
rust_iso3166 = "0.2"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sqlx = { version = "0.9", default-features = false, features = [
  "runtime-tokio",
  "postgres",
  "uuid",
  "macros",
  "migrate",
] }
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing.workspace = true
url = "2.5"
utoipa = { workspace = true, features = [
  "axum_extras",
  "preserve_order",
  "preserve_path_order",
  "non_strict_integers",
  "uuid",
  "chrono",
  "url",
] }

[lints]
workspace = true
