{
 "title": "OpenTelemetry APM",
 "description": "A language-agnostic application performance management(APM) with OpenTelemetry, Grafana, and Prometheus.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "app", "label": "Service", "query": { "query": "label_values(service_name)" } },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "label_values({service_name=\"$app\"},http_route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app\", http_route=~\"$route\"}) by(service_name)",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app\", http_route=~\"$route\"}) by(service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app\", http_response_status_code=~\"^2.*\", http_route=~\"$route\"}) by(http_response_status_code)",
     "legendFormat": "Http Status 2XX"
    },
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app\", http_response_status_code=~\"^3.*\", http_route=~\"$route\"}) by(http_response_status_code)",
     "legendFormat": "Http Status 3XX"
    },
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app\", http_response_status_code=~\"^4.*\", http_route=~\"$route\"}) by(http_response_status_code)",
     "legendFormat": "Http Status 4XX"
    },
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app\", http_response_status_code=~\"^5.*\", http_route=~\"$route\"}) by(http_response_status_code)",
     "legendFormat": "Http Status 5XX"
    },
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app\", http_response_status_code=~\"^2.*\", http_route=~\"$route\"}) by(http_response_status_code)",
     "legendFormat": "Http Status 2XX"
    },
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app\", http_response_status_code=~\"^3.*\", http_route=~\"$route\"}) by(http_response_status_code)",
     "legendFormat": "Http Status 3XX"
    },
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app\", http_response_status_code=~\"^4.*\", http_route=~\"$route\"}) by(http_response_status_code)",
     "legendFormat": "Http Status 4XX"
    },
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app\", http_response_status_code=~\"^5.*\", http_route=~\"$route\"}) by(http_response_status_code)",
     "legendFormat": "Http Status 5XX"
    }
   ]
  },
  {
   "title": "Request Distribution",
   "type": "piechart",
   "description": "request amount distribution",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app\", http_route=~\"$route\"}) by(http_request_method, http_route)",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Loading Distribution",
   "type": "piechart",
   "description": "cumulative latency distribution",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_sum{service_name=\"$app\", http_route=~\"$route\"}) by(http_request_method, http_route)",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Overall Request Rate",
   "type": "gauge",
   "description": "overall request rate per minute over last 3 minutes",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name=\"$app\", http_route=~\"$route\"}[3m])*60)"
    }
   ]
  },
  {
   "title": "Overall Error Rate",
   "type": "gauge",
   "description": "percentage of HTTP status 5xx in all requests",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app\", http_response_status_code=~\"5.*|\", http_route=~\"$route\"})/sum(http_server_request_duration_seconds_count{service_name=\"$app\", http_route=~\"$route\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "request rate per minute over last 3 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name=\"$app\", http_route=~\"$route\"}[3m])*60)  by(http_request_method, http_route)",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "PR95 Latency",
   "type": "timeseries",
   "description": "PR95 latency over last 3 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{service_name=\"$app\", http_route=~\"$route\"}[3m])) by (le, http_request_method, http_route))",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "bargauge",
   "description": "by route and http status code",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(http_server_request_duration_seconds_sum{service_name=\"$app\", http_response_status_code!=\"\", http_route=~\"$route\"} / http_server_request_duration_seconds_count{service_name=\"$app\", http_response_status_code!=\"\", http_route=~\"$route\"})",
     "legendFormat": "[{{http_response_status_code}}] {{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "description": "Details of each API",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name=\"$app\", http_route=~\"$route\"}[3m])*60) by(service_name, http_request_method, http_route)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{service_name=\"$app\", http_route=~\"$route\"}[3m])) by (le, service_name, http_request_method, http_route))"
    },
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app\", http_route=~\"$route\", http_response_status_code!~\"2.*|3.*\"}) by(service_name, http_request_method, http_route) / sum(http_server_request_duration_seconds_count{service_name=\"$app\", http_route=~\"$route\"}) by(service_name, http_request_method, http_route)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "description": "Logs of the service, filtered by `service.name`.\n\nTo explore the logs, open the menu clicking on the icon `⋮` of this panel and click on `Explore`.",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "direction": "forward",
       "expr": "service_name:\"$app\""
      }
     ]
    }
   ]
  },
  {
   "title": "Traces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Traces containing a span emitted by the service",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "limit": 20,
       "metricsQueryType": "range",
       "query": "{resource.service.name=\"$app\"} | select(status)",
       "tableType": "traces"
      }
     ]
    }
   ]
  }
 ]
}