[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[target.'cfg(target_os = "linux")']
linker = "clang"
rustflags = [
  "--cfg",
  "tokio_unstable",
  "-C",
  "target-cpu=native",
  "-Z",
  "macro-backtrace",
  "-Z",
  "threads=8",
  "-C",
  "link-arg=-fuse-ld=mold",
]

[target.'cfg(not(target_os = "linux"))']
rustflags = [
  "--cfg",
  "tokio_unstable",
  "-C",
  "target-cpu=native",
  "-Z",
  "macro-backtrace",
  "-Z",
  "threads=8",
  "-C",
  "link-arg=-fuse-ld=lld",
]
